services:
  - type: web
    name: pix-api
    env: docker
    plan: free
    healthCheckPath: /api/docs/
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: pix-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: pix-redis
          type: redis
          property: connectionString
      - key: ALLOWED_HOSTS
        value: ".onrender.com"

  - type: redis
    name: pix-redis
    plan: free
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []

databases:
  - name: pix-db
    plan: free
    databaseName: pix
    user: pix
